export const ACCOUNT_SET_TOKEN = "ACCOUNT_SET_TOKEN";
export const ACCOUNT_CLEAR_TOKEN_USER = "ACCOUNT_CLEAR_TOKEN_USER";
export const ACCOUNT_SET_USER = 'ACCOUNT_SET_USER';

export const PRODUCT_SET_PAGINATION = "PRODUCT_SET_PAGINATION";

export const STOCK_SET_CARTITEM = "STOCK_SET_CARTITEM";
export const STOCK_SET_PAGINATION = 'STOCK_SET_PAGINATION'
export const STOCK_CLEAR = "STOCK_CLEAR";
